### ISSUE TITLE
API 2.0

### ISSUE THREAD

**Issue by ai** [pd4d10/nanoid#2]
Let’s update the library to be compatible with the latest Nano ID 2.0:

- [x] Replace `~` to `-` in default alphabet
- [x] Add `non-secure` fast generator
- [x] Async API?

**Comment by pd4d10** [comment]
v0.0.5 is published, which should implement 1 and 2.

Seems Dart SDK [has no async API](https://api.dartlang.org/stable/2.0.0/dart-math/Random-class.html) for random number generator currently.

Let's keep this issue to track it.

**Comment by ai** [comment]
Async API is only for languages, that support it. You can ignore this part if it is not important for Dart.

**Comment by pd4d10** [comment]
I take a look at [random.browser.js](https://github.com/ai/nanoid/blob/master/async/random.browser.js) of nanoid, and I think we can implement this too.

It just put the following code to next tick. The `crypto.getRandomValues` itself is still sync.

**Comment by ai** [comment]
Yeap. Async random is in `async/random*` files

**Comment by pd4d10** [comment]
Async API is implemented in v0.0.6. Thanks!
